### ISSUE TITLE
Locale 'ckb' normalized to 'ku' warning in MudBlazor.Translations 2.1.0

### ISSUE THREAD

**Issue by Pvxtotal** [MudBlazor/Translations#151]
Hi,

I’ve encountered the following warning when using the `MudBlazor.Translations` package version 2.1.0 in a project:

"Package MudBlazor.Translations 2.1.0 has a resource with the locale 'ckb'. This locale has been normalized to the standard format 'ku' to prevent casing issues in the build. Consider notifying the package author about this casing issue."

It seems that a resource file or configuration in the package uses the locale 'ckb' (Central Kurdish), which is being automatically normalized to 'ku' (Kurdish) during the build process. While this normalization avoids build errors, it might not align with the intended specificity of the translation (since 'ckb' is a valid ISO 639-3 code for Central Kurdish, whereas 'ku' is a more general ISO 639-1 code).

I’d be happy to assist with more details or even a PR if needed. Let me know how you’d like to proceed!

Thanks!

**Comment by meenzen** [comment]
Thanks for reporting the issue. This should be fixed in the next release.

14fdd17c5d0c1a9ba205d3b9c138c21f372c704b

**Comment by w3ori** [comment]
@meenzen 
I still get this error when I build my project. I don't use `ckb` in my project at all.
```
Package MudBlazor.Translations 2.5.0 has a resource with the locale 'ckb'. This locale has been normalized to the standard format 'ku' to prevent casing issues in the build. Consider notifying the package author about this casing issue.
```

**Comment by meenzen** [comment]
Unfortunately there's nothing we can do about it until Microsoft decides to change how languages are handled in the sdk. Just ignore the warning.

**Comment by sardar97** [comment]
> [@sardar97](https://github.com/sardar97) was suppose to make a report bug for MSFT

ckb is now in the CultureInfo.

this code compiled with **.NET 10**

```
using System.Globalization;

var cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
foreach (var culture in cultures.Where(x=>x.Name.Contains("ku") || x.Name.Contains("ckb") ))
{
    Console.WriteLine(culture.Name);
} 

var info = CultureInfo.GetCultureInfo("ckb");
Console.WriteLine("-----------------------------------");
Console.WriteLine("Name : "+info.Name);
Console.WriteLine("Calendar : "+info.Calendar);
Console.WriteLine("CompareInfo : "+info.CompareInfo);
Console.WriteLine("CultureTypes : "+info.CultureTypes);
Console.WriteLine("DateTimeFormat : "+info.DateTimeFormat);
Console.WriteLine("DisplayName : "+info.DisplayName);
Console.WriteLine("EnglishName : "+info.EnglishName);
Console.WriteLine("IetfLanguageTag : "+info.IetfLanguageTag);
Console.WriteLine("IsNeutralCulture : "+info.IsNeutralCulture);
Console.WriteLine("NumberFormat : "+info.NumberFormat);
Console.WriteLine("NativeName : "+info.NativeName);
```



**Output :**

```
ckb
ckb-IQ
ckb-IR
ku
ku-Latn
ku-Latn-IQ
ku-Latn-SY
ku-Latn-TR
ku-TR
-----------------------------------
Name : ckb
Calendar : System.Globalization.GregorianCalendar
CompareInfo : CompareInfo - ckb
CultureTypes : NeutralCultures, UserCustomCulture
DateTimeFormat : System.Globalization.DateTimeFormatInfo
DisplayName : Kurdish, Sorani
EnglishName : Kurdish, Sorani
IetfLanguageTag : ckb
IsNeutralCulture : True
NumberFormat : System.Globalization.NumberFormatInfo
NativeName : کوردیی ناوەندی
```

**Comment by w3ori** [comment]
I still get this Warning in .NET 10.

<img width="1236" height="65" alt="Image" src="https://github.com/user-attachments/assets/77894283-8210-4023-8adc-5214f813bd6b" />

**Comment by Frulfump** [comment]
> > [@sardar97](https://github.com/sardar97) was suppose to make a report bug for MSFT
> 
> ckb is now in the CultureInfo.
> 
> this code compiled with **.NET 10**
> 
> ```
> using System.Globalization;
> 
> var cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
> foreach (var culture in cultures.Where(x=>x.Name.Contains("ku") || x.Name.Contains("ckb") ))
> {
>     Console.WriteLine(culture.Name);
> } 
> 
> var info = CultureInfo.GetCultureInfo("ckb");
> Console.WriteLine("-----------------------------------");
> Console.WriteLine("Name : "+info.Name);
> Console.WriteLine("Calendar : "+info.Calendar);
> Console.WriteLine("CompareInfo : "+info.CompareInfo);
> Console.WriteLine("CultureTypes : "+info.CultureTypes);
> Console.WriteLine("DateTimeFormat : "+info.DateTimeFormat);
> Console.WriteLine("DisplayName : "+info.DisplayName);
> Console.WriteLine("EnglishName : "+info.EnglishName);
> Console.WriteLine("IetfLanguageTag : "+info.IetfLanguageTag);
> Console.WriteLine("IsNeutralCulture : "+info.IsNeutralCulture);
> Console.WriteLine("NumberFormat : "+info.NumberFormat);
> Console.WriteLine("NativeName : "+info.NativeName);
> ```
> 
> 
> 
> **Output :**
> 
> ```
> ckb
> ckb-IQ
> ckb-IR
> ku
> ku-Latn
> ku-Latn-IQ
> ku-Latn-SY
> ku-Latn-TR
> ku-TR
> -----------------------------------
> Name : ckb
> Calendar : System.Globalization.GregorianCalendar
> CompareInfo : CompareInfo - ckb
> CultureTypes : NeutralCultures, UserCustomCulture
> DateTimeFormat : System.Globalization.DateTimeFormatInfo
> DisplayName : Kurdish, Sorani
> EnglishName : Kurdish, Sorani
> IetfLanguageTag : ckb
> IsNeutralCulture : True
> NumberFormat : System.Globalization.NumberFormatInfo
> NativeName : کوردیی ناوەندی
> ```

Which version of the .NET 10 SDK are you building with?

**Comment by ScarletKuro** [comment]
I don't think the fix is merged in the SDK yet?
https://github.com/dotnet/sdk/pull/53817
That the `CultureInfo` returns info for `ckb` doesn't mean the SDK part is ready.
My suggestion is to forward all the questions to MSFT directly, instead of discussing it here, as we can't help you.

**Comment by Keldoran75** [comment]
I got this warning in Visual Studio:
Package MudBlazor.Translations 3.3.0 has a resource with the locale 'ckb'. This locale has been normalized to the standard format 'ku' to prevent casing issues in the build. Consider notifying the package author about this casing issue.

- MudBlazor.Translations: 3.3.0
- .NET target framework: net10.0
- .NET SDK: 10.0.302
